name: get_up
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.3
  intl: ^0.19.0
  provider: ^6.1.2
  confetti: ^0.7.0

  # --- THIS IS THE FIX ---
  # We are forcing older, stable versions that are compatible
  fl_chart: ^0.66.0
  flutter_local_notifications: ^16.3.0
  flutter_timezone: ^1.0.0
  # --- END FIX ---

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.9
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "legacy"
  ios: true
  image_path: "assets/images/logo.png"
  adaptive_icon_padding: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/logo.png
